# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  rootDir: 'my-app'
  buildDir: '$(rootDir)/build'

trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd $(rootDir)
    npm install
    echo Line a.
    echo Line b.
    npm run build
    echo Line c.
    cd ..
  displayName: 'npm install and build'

- script: |
    cd $(rootDir)
    npm run build
    echo Line a.
    echo Line b.
    npm install
    echo Line c.
    cd ..

- script: |
    echo Line 1.
    echo Line 2.
    echo Line 3.

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      cd $(rootDir)
      npm run build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'